name: LendSmart CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  # Infrastructure Validation
  infrastructure-lint:
    name: Infrastructure Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Format Check
        run: |
          cd infrastructure/terraform
          terraform fmt -check -recursive

      - name: Terraform Init
        run: |
          cd infrastructure/terraform
          terraform init -backend=false

      - name: Terraform Validate
        run: |
          cd infrastructure/terraform
          terraform validate

      - name: Install validation tools
        run: |
          pip install yamllint ansible-lint

      - name: Validate Kubernetes Manifests
        run: |
          yamllint infrastructure/kubernetes/

      - name: Validate Ansible Playbooks
        run: |
          cd infrastructure/ansible
          ansible-lint playbooks/*.yml || true

  lint:
    name: Code Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci
          cd smart-contracts && npm ci
          cd ../backend && npm ci
          cd ../web-frontend && npm ci

      - name: Lint Smart Contracts
        run: |
          cd smart-contracts
          npx solhint 'contracts/**/*.sol'

      - name: Lint Backend
        run: |
          cd backend
          npx eslint .

      - name: Lint Frontend
        run: |
          cd web-frontend
          npx eslint .

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci
          cd smart-contracts && npm ci
          cd ../backend && npm ci
          cd ../web-frontend && npm ci

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn pandas numpy joblib

      - name: Test Smart Contracts
        run: |
          cd smart-contracts
          npx hardhat test

      - name: Test Backend
        run: |
          cd backend
          npm test

      - name: Test Frontend
        run: |
          cd web-frontend
          npm test

      - name: Test AI Risk Model
        run: |
          cd ml-model
          python -m unittest discover tests

  deploy-testnet:
    name: Deploy to Testnet
    runs-on: ubuntu-latest
    needs: [test, infrastructure-lint]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: |
          cd smart-contracts
          npm ci

      - name: Deploy to Sepolia Testnet
        env:
          PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
        run: |
          cd smart-contracts
          npx hardhat run scripts/deploy.js --network sepolia

      - name: Verify Contract on Etherscan
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: |
          cd smart-contracts
          npx hardhat verify --network sepolia $(cat .deployed-address)

      - name: Update Deployment Info
        run: |
          echo "Contracts deployed to Sepolia testnet"
          echo "DEPLOYED_ADDRESS=$(cat smart-contracts/.deployed-address)" >> $GITHUB_ENV
