---
# roles/webserver/tasks/main.yml

- name: Install web server packages (RedHat)
  ansible.builtin.yum:
    name:
      - nginx
    state: present
  when: ansible_os_family == "RedHat"

- name: Install web server packages (Debian)
  ansible.builtin.apt:
    name:
      - nginx
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Create web application directory
  ansible.builtin.file:
    path: /var/www/{{ app_name }}
    state: directory
    owner: nginx
    group: nginx
    mode: "0755"

- name: Configure Nginx
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/{{ app_name }}.conf
    owner: root
    group: root
    mode: "0644"
    validate: nginx -t -c %s
  notify: Restart Nginx

- name: Start and enable Nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes
