apiVersion: v1
kind: Service
metadata:
  name: lendsmart-frontend
  namespace: default
  labels:
    app: lendsmart-frontend
    component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: lendsmart-frontend
