stages:
  - build
  - test
  - security_scan
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

.build_template:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHORT_SHA

build_frontend:
  extends: .build_template
  variables:
    DOCKERFILE_PATH: ./frontend/Dockerfile
  rules:
    - changes: [frontend/**/*]

build_backend:
  extends: .build_template
  variables:
    DOCKERFILE_PATH: ./backend/Dockerfile
  rules:
    - changes: [backend/**/*]

.test_template:
  stage: test
  image: python:3.9-slim-buster # Or appropriate language image
  script:
    - echo "Running tests..."
    - # Add actual test commands here

test_frontend:
  extends: .test_template
  rules:
    - changes: [frontend/**/*]

test_backend:
  extends: .test_template
  rules:
    - changes: [backend/**/*]

security_scan:
  stage: security_scan
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker pull $CI_REGISTRY/$CI_PROJECT_PATH/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHORT_SHA
    - # Example: Trivy scan for vulnerabilities
    - docker run --rm -v $CI_PROJECT_DIR:/root/.cache/ trivy/trivy:latest image --exit-code 1 --severity HIGH $CI_REGISTRY/$CI_PROJECT_PATH/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHORT_SHA
  allow_failure: true # Allow failure for now, but should be false in production

deploy_dev:
  stage: deploy
  image: alpine/helm:3.8.1 # Or appropriate image with kubectl and helm
  script:
    - kubectl config use-context your-dev-cluster-context
    - helm upgrade --install lend-smart-dev ./helm/lend-smart --namespace dev -f ./helm/lend-smart/values-dev.yaml
  environment:
    name: development
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"

deploy_staging:
  stage: deploy
  image: alpine/helm:3.8.1
  script:
    - kubectl config use-context your-staging-cluster-context
    - helm upgrade --install lend-smart-staging ./helm/lend-smart --namespace staging -f ./helm/lend-smart/values-staging.yaml
  environment:
    name: staging
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

deploy_prod:
  stage: deploy
  image: alpine/helm:3.8.1
  script:
    - kubectl config use-context your-prod-cluster-context
    - helm upgrade --install lend-smart-prod ./helm/lend-smart --namespace prod -f ./helm/lend-smart/values-prod.yaml
  environment:
    name: production
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
  when: manual


